apiVersion: apps/v1
kind: Deployment
metadata:
  name: led-light-mapper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: led-light-mapper
  template:
    metadata:
      labels:
        app: led-light-mapper
    spec:
      nodeName: latelee.org.ttucon-2142ec #edge-node2
      hostNetwork: true
      containers:
      - name: led-light-mapper-container
        image: latelee/led-light-mapper:v1.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-edge-node2
      restartPolicy: Always

